chain_admin = """1dc50eb5d9fd2a916e44eab5c438ab52849284d1"""

chain_admin_nonce = """0"""

consortium_cert = """-----BEGIN CERTIFICATE-----
MIIDgjCCAmqgAwIBAgIJAK2yyZ7dM9h5MA0GCSqGSIb3DQEBCwUAMHcxJDAiBgNV
BAMMG3Jvb3QuYmFhcy5jb25mbHV4LWNoYWluLm9yZzEWMBQGA1UECgwNY29uZmx1
eC1jaGFpbjEQMA4GA1UECwwHaXQtZGVwdDELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yNTA1MjIwNjQyMzRaFw0zNTA1MjIxNTU5NTla
MHgxKjAoBgNVBAMMIWNvbnNvcnRpdW0uYmFhcy5jb25mbHV4LWNoYWluLm9yZzEW
MBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UECwwCcmQxCzAJBgNVBAcMAlNI
MQswCQYDVQQIDAJTSDELMAkGA1UEBhMCQ04wggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQCxCFj4Oykf7tTWd1P8j2lH+3QZ+CiO9OZWQG0Y93+nwlmPofph
kaSUUkhhK7O9EwFJGPKhCB/MktMYxH0rC34Gm34mJt6knNtTtjRufj73K8Z9AOJ1
D0QNUbaowmaT1jepKXHyl4esG1C7OkiL+LytW5uDfpFenZH95ORjxTARMMIgcHWu
6A7srJ0iA8k1mWwTiWLljAmie8udWIzRwG81YoWsP21/K+woy0CpKyzjV/3ByAHm
h4Xz7xke2HjnhF60L1v8AxbPzI/MhE1xCYTMlWt4Xi9GVqD2Bc5fwIOBQt9rjcyE
XizaJTfRZXmv5sOaaxRwVEH/jFeutUbbkJcbAgMBAAGjEDAOMAwGA1UdEwQFMAMB
Af8wDQYJKoZIhvcNAQELBQADggEBACPz6zYZoN67u9BpJfUTLgmeKHTc4vDeb/Io
HUmpM2QM8M96jPLtAthc75WzeqalmDYg+TZKBXs7e8pP4gG/3vSakq0+J/lm8XC0
bRuMyC4Tqiquff/R7dkzV7MLmAroQJPE7wawAvdi5SjfESpUItBcfgROvjyUb/Sx
ceI05a66cE9woYkDeWUTaVn90hFhMq23ph6uYhOJtdO0ZpbCDvPlBVssUJMIBtoO
0j46BWNvhrFe0HhTrVC07r1RhRctZVuT94zCPoqxtBrudIMweja5G+2C7U8CjgZn
NSHjBVfBJH0GC2Y1x0UVduG9CmxzZj8v01d0F3YA2hQaLrL+Mpo=
-----END CERTIFICATE-----
"""

consortium_nodes = """cfxnode://edaff44707bfce4720dbbb7e33467eedd548c650145b0e320d78d1856fd68a17e34ca9e88ec7ec00ee57d202f882db5037ee36de5e3ffe188bc07741aee9b284@139.224.187.155:30006,cfxnode://172133c264982a88c3fd0aa6dc354930659b94cf99a6a8417c8ebd673d3f35ac5c3e92aef95b94e78a73bf9c12a188b8b38f436cdcfd841ec5aa90c00bebaf8d@47.116.165.80:30007,cfxnode://516dfd97fab890fe4e88987aa5831387c964faec3c3af6df3b8a064f2ad46fac9bca171bc618bb50337baf168d5329715e566710e7833ee0b94ef4f1e091f554@47.116.165.80:30008,cfxnode://32ae57bbdbabafdd0e32fc031aa3dafd3388c9cd39e759767d6a738e7f6b89a68caec835cb0013931975e288795e9c1423c621696905c85b080d188731d568e4@139.224.187.155:30005"""

consortium_nodes_digest = "3726862378af7c645a48f0a78df11f80a4581c2af13a035b0e78094fddfdb60a1c1ceac62555166e40a0046877d6abfab2279b08859be6ed7787c981e52e58951b"

consortium_keypair = "32ae57bbdbabafdd0e32fc031aa3dafd3388c9cd39e759767d6a738e7f6b89a68caec835cb0013931975e288795e9c1423c621696905c85b080d188731d568e4,cfcd96830b9c2d05009b76ad3f92309f3a52fc9a1fc04fb2e83f3f47bd737ae1"

grpc_server_cert = """-----BEGIN CERTIFICATE-----
MIIDezCCAmOgAwIBAgIJAJ1wjG6P7PgLMA0GCSqGSIb3DQEBCwUAMHcxJDAiBgNV
BAMMG3Jvb3QuYmFhcy5jb25mbHV4LWNoYWluLm9yZzEWMBQGA1UECgwNY29uZmx1
eC1jaGFpbjEQMA4GA1UECwwHaXQtZGVwdDELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yNTA1MjIwNjQxMDhaFw0zNTA1MjIxNTU5NTla
MHExIzAhBgNVBAMMGnJwYy5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMRYwFAYDVQQK
DA1jb25mbHV4LWNoYWluMQswCQYDVQQLDAJyZDELMAkGA1UEBwwCU0gxCzAJBgNV
BAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAIMMbJpiAWAAwpFjliZ0biCm0TSrATWCKgVV0oWQe+ZbYP1x1CJIczkYmuC2
EcOgPkCx7z21Xd5ayrAaMALHC/iFx7fA1aUsJrgxG7n43cZ6Lnmkka14LRFOH2Ve
zFG4QKbX9Hyyi0/yoawaYOjelbbH3QJvUfrOJVClvLziyhjC9kB5+Qhn7ZnlbCOd
J67yqhfbWqlXUctbJQmgP9N3vUcVitssfzNb7a8PRuCK362LW5UEOcZbXE7qtUcq
TQFM3wn4XymMBxvJdVyjzkx3WwXIwSvQL42oSm1TKpFdleRiY4CSk+rP1/olm/SH
ElUYQKDQRDB/xuFrcwXsrTI61x0CAwEAAaMQMA4wDAYDVR0TBAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAQEAYmeMPPGputWLQLLnUTBUeF9tQwxT8nXplZylD5yjQRww
TtuIb8X0Ea3npsvPBGRvvcfwrYzpytuI1SuIimYY3upggSsZThQLQP2+QCeAWNDK
EOO3nAZn18gJZ8rl2HGF9R2zSI+GTJX783lvbHrikZc61Jv3V0nbPWKivm8YUxua
qDOAa4ZJrI4PzDVSoxuD8nFHgfUmlsoYMTiLmIuc6+BAF9q6znCFNYPdgu2ZlmAy
B0qkv3fvYMeW+xQs/JUpRBxj28TtpJaXrV5uTGoQK8laxhRTB9jy50OTnUrtSO6B
BExQUQyhGoImQpX7+2q24zLZBMaagd0lxFtyPrhucg==
-----END CERTIFICATE-----
"""

grpc_server_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAgwxsmmIBYADCkWOWJnRuIKbRNKsBNYIqBVXShZB75ltg/XHU
IkhzORia4LYRw6A+QLHvPbVd3lrKsBowAscL+IXHt8DVpSwmuDEbufjdxnoueaSR
rXgtEU4fZV7MUbhAptf0fLKLT/KhrBpg6N6VtsfdAm9R+s4lUKW8vOLKGML2QHn5
CGftmeVsI50nrvKqF9taqVdRy1slCaA/03e9RxWK2yx/M1vtrw9G4IrfrYtblQQ5
xltcTuq1RypNAUzfCfhfKYwHG8l1XKPOTHdbBcjBK9AvjahKbVMqkV2V5GJjgJKT
6s/X+iWb9IcSVRhAoNBEMH/G4WtzBeytMjrXHQIDAQABAoIBAHAarcD3e9Ojcs4q
0eR9j0PxUF/stXEPs2CzBQ9rBQKPQw4sVNsq/R5ntP3r4pBlwTtYu58fSniPVHqH
PHDz04K69plzpY/RkCHbKKvTf+xs0tsOc+xgNLVsDiGKkeCKbQwNC0Gs/s3acoEm
Y6Zx2sLsgFy32/pgZL1zulwe6eF5kiB0VH4SWvfH5aFybcilZZl1OsoKdDtq2ElT
PTD8msNxaznzkwUTfMhmjUDIspX9JQtnywZcNcFkY1DWRvX2Wik9X+HdrE1lzd+J
RlxftwPJzBLTypt5r4k8wJ5YvtHxD6zoVj4Ogo/GQFw4KbhIiUyjaJwd4xXGI9OP
MMbYl4ECgYEA0fNK2d338S+XABo+FlNt/d/1QRvElJilG9stEok3x+DPAijUKN5O
WQ+Osrct7b+WVArt44rfD8PFxu+s1cbKpUFpxcZFa7exvJoctHHDghh3kS6wZj8n
wunSzemUYO5No4LixsReB1VfqRAKFJ615hViXyuOaPHHUBH4tzqZD+ECgYEAn8rL
zPKm2Y0OckbzvG7qP67OS2uVzm1jN+hT2Yw70pqp67qMCp7CgukyNFrMR1bADRpr
WZ/Z/69+8ENdHnodnuDf6RriRDveIo4CmMj9UmECcmu/bS41OgF77JWfyQioQt2X
F6zBCY+o2OKmdAll8KykKMavCmbjipPBPKYV3r0CgYEAvJoa/pZ5GnAO7OemKLYv
0+VxU1jXgkmR4PFGjyU3N9ZK//yfgksaBMWGAiOuHaqDJ+Jdi5AADBBpReme0Lfw
6P1XQHR5fmeZQf0LlkmwQNkr5/8SNfe8B0u3tISFZ4ILurxkbfyPH3VhJuWiuJ1O
eG9zXF0rZDj2PIa4cBky0OECgYAWrhwbLN3Nxx2jzrpNppiNDWyue8i5kgEhMFKm
cCcVj2pK0SGLaFlHZ33+vFx+S6vasENIZ03z4p7rz0PqTX7izBw749r1wGGZGfr4
YJ7EEIzeXLjA8GwRnaBPRjV1vUrUossNSzHi/4cBsbnagnL7pCVwvDKgEVZ+ltY4
m4JDKQKBgDEO6MfAEXtDQCorsp6mI0h0+kkxVO1sNGcqa/kVYfVyuL1SMKeVPqhg
arvjFzn0+9CFsPFgIsqtt3vu6POAUldq9HjxPQKGFntXbYeGkKi4VwF9QMdINOAB
JxVDnIdP9/QTqWSPKL2p1QVjZFOsxr6iv5xsF4JxYF0MBRC6l19h
-----END RSA PRIVATE KEY-----
"""

baas_ca_url = "http://192.168.1.24:9797/"

mode = "tg_archive"

start_mining = true

root_ca = """-----BEGIN CERTIFICATE-----
MIIDgTCCAmmgAwIBAgIJAOffKdSROBL7MA0GCSqGSIb3DQEBCwUAMHcxJDAiBgNV
BAMMG3Jvb3QuYmFhcy5jb25mbHV4LWNoYWluLm9yZzEWMBQGA1UECgwNY29uZmx1
eC1jaGFpbjEQMA4GA1UECwwHaXQtZGVwdDELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yNTA1MjIwNjQxMDhaFw0zNTA1MjIxNTU5NTla
MHcxJDAiBgNVBAMMG3Jvb3QuYmFhcy5jb25mbHV4LWNoYWluLm9yZzEWMBQGA1UE
CgwNY29uZmx1eC1jaGFpbjEQMA4GA1UECwwHaXQtZGVwdDELMAkGA1UEBwwCU0gx
CzAJBgNVBAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAIFvQVTvdgWTR6l2jR+kM69XAwuMlbVYGQGNmGwoyH63JtYb4RQ7
p8Spgvve1ICkcBMjerW6FC8N7K3tjMzAIPf136Kn812xT1X6lEDngry1oo14UaWQ
2yJZnuL8Iq50bzBXG8iU87bW9MtlI2SrWfpVLIUPDodjtZJgIcXHm02A3Wnpqlgp
sPnYhkpZgEZLV695I916fx/IKpwWjuqhGVc6q7aS+4lPfK1McrUwqhhvRpwsk7Al
F9de1fWSbEifA09W8H5v0kuuZxkhKkKX9pOo4Eo0MgHf9+R6o82E7HPYzwyyb6vp
Z8fOGf00uE1AiVhqDoT5X90Re5RSWtxOYdcCAwEAAaMQMA4wDAYDVR0TBAUwAwEB
/zANBgkqhkiG9w0BAQsFAAOCAQEAIo8UzERb6jq0mGJPpixiIKZYN3dlX8JpS0z8
tjZJDcmDcr/e1wSK+4BqV7cs4ci3u/Mui4nzpahsWZ/PopZlHxWEe+lufnN8tCG9
W0QgHqFxX4frqQkjAejoHFQRtIH5x4h+F5d1xduzGKCtxoqsVs23Dd1FN7FtEKjK
TgUAqWqW7UU10T74y672rLcJ/fGMAnTXI0qRovJE16zqyUou5ec0fnW1On7E4z7e
3KnMiPMEWm91FDs0JcLmz43nIgaQugGfD7TuE8ZQWhTIBjMe+E3suzFI5/AJbSQG
xmfIofpFe07iyri6SzTBmNFDA6BG2roY+Xk8kqkGlu8oOLjIUg==
-----END CERTIFICATE-----
"""

root_ca_signatures = """baada947d20ea2cab21d266e67fecdf020a1d70491b554f66978032a06c0c0b044ed51737e3a49d7e3aac7c764a71cb2f42ae47aef7571728c20b8dc5f6ed1091b"""

bin_name =  "conflux_30005"

