version: '3'
services:

  exporter:
    restart: always
    image: prom/node-exporter:latest
    container_name: baas_monitor_exporter
    networks:
      - baas_monitor_net

  prometheus:
    restart: always
    image: prom/prometheus:latest
    container_name: baas_monitor_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_persist:/prometheus
    depends_on:
      - exporter
    networks:
      - baas_monitor_net
    links:
      - exporter

networks:
  baas_monitor_net:

volumes:
  prometheus_persist:
