apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    uid: 'my_unique_uid'
    url: "http://baas_monitor_prometheus:9090"
    password:
    user:
    database:
    basicAuth:
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault:
    jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     timeInterval: 10s
     httpMode: 'GET'
    version: 1
    editable: false